# Generated by Django 5.2.8 on 2026-01-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('pronvincia', models.CharField(max_length=100)),
                ('fecha_nacimineto', models.DateField()),
            ],
        ),
    ]
