# Generated by Django 5.2.8 on 2026-02-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_lector_lector_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='portada',
            field=models.ImageField(null=True, upload_to='portadas/'),
        ),
    ]
