# Generated by Django 5.2.8 on 2026-02-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookinstance_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
