# Generated by Django 5.2.8 on 2026-02-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bookinstance_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
