# Generated by Django 5.2.8 on 2026-02-12 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_bookinstance_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bookinstance')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.lector')),
            ],
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='reservadores',
            field=models.ManyToManyField(related_name='reservas', through='catalog.Reservation', to='catalog.lector'),
        ),
    ]
