# Generated by Django 5.2.8 on 2026-02-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_reservation_bookinstance_reservadores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='lector',
            new_name='usuario_reservador',
        ),
    ]
