# Generated by Django 5.2.8 on 2026-02-12 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_lector_reservation_usuario_reservador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='book_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', related_query_name='ejemplaresquery', to='catalog.bookinstance'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='usuario_reservador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectores', related_query_name='lectoresquery', to='catalog.lector'),
        ),
    ]
