# Generated by Django 5.2.8 on 2026-02-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_reservation_book_instance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'permissions': (('can_mark_returned', 'Set book as returned'), ('bibliotecario_poder', 'Permiso alto rango'), ('carnet_lector', 'permiso de lector'))},
        ),
    ]
