# Generated by Django 5.2.8 on 2026-02-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_lector_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='leidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lector',
            name='penalizado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
