# Generated by Django 5.2.8 on 2026-02-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_lector_leidos_lector_penalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
